import Head from 'next/head';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {BiCodeAlt} from 'react-icons/bi'
import {CgWebsite} from 'react-icons/cg'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiOutlineMail} from 'react-icons/ai';
import Image from 'next/image';
import project1 from '../public/project1.png';
import project2 from '../public/project2.png';
import project3 from '../public/project3.png';
import project4 from '../public/project4.png';
import project5 from '../public/project5.png';
import project6 from '../public/project6.jpeg';
import { useState } from 'react';
import { motion as m } from 'framer-motion';
import {container, item} from '../animation';
import { useFormik } from 'formik';
import * as Yup from 'yup';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      message: '',
    },

    //Validation Form
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, 'Name must be 20 characters or less.')
        .required('Name is required'),
      email: Yup.string()
        .email('Email address invalid')
        .required('Email is required'),
      message: Yup.string()
      .max(1000, 'Message is too long.')
      .required('Message field is required')
    }),

    onSubmit: (values) => {
      console.log(values)
    }
  })


  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Brian Sanchez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;700&family=Poppins:wght@200;400;500;700&display=swap" rel="stylesheet" />
      </Head>
      <main
      className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between dark:text-white'>
            <h1 className='text-xl font-burtons'>portfolio</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer' /></li>
              <m.li
              transition={{duration: 0.2, ease: 'easeOut'}}
              whileHover={{ scale: 1.1 }}
              >
                <a className='bg-gradient-to-r from-cyan-500 to-purple-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a>
              </m.li>
            </ul>
          </nav>
          <m.div
          animate={{y: '0%'}}
          initial={{y:'100%'}}
          transition={{duration: 0.75, ease: 'easeOut'}}
          exit={{opacity: 1}}
          >
          <div
            className='text-center p-10 '>
            <div className='overflow-hidden'>
              <m.h2
              animate={{y:0}}
              initial={{y:'100%'}}
              transition={{delay: 0.5, duration: 0.5}}
              className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400 font-poppins'>Brian Sanchez</m.h2>
            </div>
            <h3 className='text-2xl py-2 md:text-3xl font-poppins dark:text-white'>Software Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto font-poppins dark:text-gray-200'>I'm a <span className="text-teal-500">self-driven</span> and <span className="text-teal-500">solution-centric</span> Software Engineer, who’s highly <span className="text-teal-500">committed</span> to developing and <span className="text-teal-500">implementing</span> software solutions to help <span className="text-teal-500">achieve</span> company goals. High aptitude for <span className="text-teal-500">resolving</span> technical issues and <span className="text-teal-500">integrating</span> best coding practices to meet the <span className="text-teal-500">user's needs.</span></p>
          </div>
          <div
            className='text-5xl flex justify-center gap-16 py-3 pb-12 text-gray-600'>
            <m.div
              transition={{duration: 0.3, ease: 'easeOut'}} 
              whileHover={{ scale: 1.2 }}>
              <AiFillGithub className='hover:text-black dark:hover:text-white cursor-pointer' />
            </m.div> 
            <m.div 
              transition={{duration: 0.3, ease: 'easeOut'}}
              whileHover={{ scale: 1.2 }}> 
              <AiFillTwitterCircle className='hover:text-blue-400 cursor-pointer' />
            </m.div>
            <m.div 
              transition={{duration: 0.3, ease: 'easeOut'}}
              whileHover={{ scale: 1.2 }}>
              <AiFillLinkedin className='hover:text-blue-700 cursor-pointer' />
            </m.div>
          </div>
          </m.div>
        </section>
        <section>
          <div>
            <h3 className='text-4xl py-1 text-center text-teal-600 dark:text-teal-400 font-poppins font-medium'>Projects</h3>
          </div>
          <div
            className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <m.div
              variants={container}
              initial='hidden'
              whileInView='visible'
              className='basis-1/3 flex-1 group relative'>
              <Image variants={item} src={project6} className='group-hover:opacity-10 rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} alt='' />
              <div className='hidden group-hover:block absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]'>
                <h3 className='text-center text-3xl font-poppins font-bold dark:text-white'>Mind Blogging</h3>
                <div className='flex justify-center items-center gap-10 py-6'>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-2 font-poppins justify-center items-center flex gap-1'>
                    Code<BiCodeAlt />
                  </Link>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-3 font-poppins justify-center items-center flex gap-1'>
                    Live<CgWebsite />
                  </Link>
                </div>
              </div>
            </m.div>
            <m.div
              variants={container}
              initial='hidden'
              whileInView='visible'
              className='basis-1/3 flex-1 group relative'>
              <Image variants={item} src={project5} className='group-hover:opacity-10 rounded-lg object-cover shadow-xl' width={'100%'} height={'100%'} alt='' />
              <div className='hidden group-hover:block absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]'>
                <h3 className='text-center text-3xl font-poppins font-bold dark:text-white'>Pokemon Rock, Paper, & Scissors</h3>
                <div className='flex justify-center items-center gap-10 py-6'>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-2 font-poppins justify-center items-center flex gap-1'>
                    Code<BiCodeAlt />
                  </Link>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-3 font-poppins justify-center items-center flex gap-1'>
                    Live<CgWebsite />
                  </Link>
                </div>
              </div>            
            </m.div>
            <m.div
              variants={container}
              initial='hidden'
              whileInView='visible'
              className='basis-1/3 flex-1 group relative'>
              <Image variants={item} src={project4} className='group-hover:opacity-10 rounded-lg object-cover shadow-xl cursor-pointer' width={'100%'} height={'100%'} alt='' />
              <div className='hidden group-hover:block absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]'>
                <h3 className='text-center text-3xl font-poppins font-bold dark:text-white'>Xtreme Sports Meetup</h3>
                <div className='flex justify-center items-center gap-10 py-6'>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-2 font-poppins justify-center items-center flex gap-1'>
                    Code<BiCodeAlt />
                  </Link>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-3 font-poppins justify-center items-center flex gap-1'>
                    Live<CgWebsite />
                  </Link>
                </div>
              </div>            
            </m.div>
            <m.div 
              variants={container}
              initial='hidden'
              whileInView='visible'
              className='basis-1/3 flex-1 group relative'>
              <Image variants={item} src={project3} className='group-hover:opacity-10 rounded-lg object-cover shadow-xl cursor-pointer' width={'100%'} height={'100%'} alt='' />
              <div className='hidden group-hover:block absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]'>
                <h3 className='text-center text-3xl font-poppins font-bold dark:text-white'>theSpot</h3>
                <div className='flex justify-center items-center gap-10 py-6'>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-2 font-poppins justify-center items-center flex gap-1'>
                    Code<BiCodeAlt />
                  </Link>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-3 font-poppins justify-center items-center flex gap-1'>
                    Live<CgWebsite />
                  </Link>
                </div>
              </div>             
            </m.div>
            <m.div
              variants={container}
              initial='hidden'
              whileInView='visible'            
              className='basis-1/3 flex-1 group relative'>
              <Image variants={item} src={project2} className='group-hover:opacity-10 rounded-lg object-cover shadow-xl cursor-pointer' width={'100%'} height={'100%'} alt='' />
              <div className='hidden group-hover:block absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]'>
                <h3 className='text-center text-3xl font-poppins font-bold dark:text-white'>Game Lord</h3>
                <div className='flex justify-center items-center gap-10 py-6'>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-2 font-poppins justify-center items-center flex gap-1'>
                    Code<BiCodeAlt />
                  </Link>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-3 font-poppins justify-center items-center flex gap-1'>
                    Live<CgWebsite />
                  </Link>
                </div>
              </div>            
            </m.div>
            <m.div
              variants={container}
              initial='hidden'
              whileInView='visible'           
              className='basis-1/3 flex-1 group relative'>
              <Image variants={item} src={project1} className='group-hover:opacity-10 rounded-lg object-cover shadow-xl cursor-pointer' width={'100%'} height={'100%'} alt='' />
              <div className='hidden group-hover:block absolute top-[50%] left-[50%] translate-x-[-50%] translate-y-[-50%]'>
                <h3 className='text-center text-3xl font-poppins font-bold dark:text-white'>Leopard Tech-O</h3>
                <div className='flex justify-center items-center gap-10 py-6'>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-2 font-poppins justify-center items-center flex gap-1'>
                    Code<BiCodeAlt />
                  </Link>
                  <Link href='' className='text-white bg-teal-600 rounded-lg text-lg py-2 px-3 font-poppins justify-center items-center flex gap-1'>
                    Live<CgWebsite />
                  </Link>
                </div>
              </div>            
            </m.div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-4xl py-1 flex justify-center items-center gap-2 text-teal-600 dark:text-teal-400 font-poppins font-medium'>Skills<BiCodeAlt /></h3>
            {/* <p className='text-md py-2 leading 8 text-gray-800 dark:text-gray-200'>lorem ipsum</p> */}
          </div>
          <m.div 
            variants={container}
            initial='hidden'
            whileInView='visible'
            className='lg:flex gap-10'>
            {/* <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'> */}
              <div variants={item} className='text-5xl flex flex-wrap flex-row gap-10 py-10 lg:px-10 lg:flex-row lg:flex-wrap dark:bg-white rounded-lg shadow-lg my-10 px-2'>
              <i className="devicon-html5-plain colored"></i>
              <i className="devicon-css3-plain colored"></i>
              <i className="devicon-javascript-plain colored"></i>
              <i className="devicon-jquery-plain colored"></i>
              <i className="devicon-express-original colored"></i>
              <i className="devicon-mongodb-plain colored"></i>
              <i className="devicon-python-plain colored"></i>
              <i className="devicon-django-plain colored"></i>
              <i className="devicon-postgresql-plain colored"></i>
              <i className="devicon-react-original colored"></i>
              <i className="devicon-redux-original colored"></i>
              <i className="devicon-bootstrap-plain colored"></i>
              <i className="devicon-materialui-plain colored"></i>
              <i className="devicon-git-plain colored"></i>
              <i className="devicon-github-original colored"></i>
              <i className="devicon-figma-plain colored"></i>
              <i className="devicon-npm-original-wordmark colored"></i>
              <i className="devicon-nextjs-original colored"></i>
              <i className="devicon-firebase-plain colored"></i> 
              <i className="devicon-tailwindcss-plain colored"></i>
              <i className="devicon-wordpress-plain colored"></i>
              </div>
            {/* </div> */}
          </m.div>
        </section>
        <section>
          <div>
            <h3 className='text-4xl py-1 flex justify-center items-center gap-2 text-teal-600 dark:text-teal-400 font-poppins font-medium'>Get In Touch<AiOutlineMail /></h3>
          </div>
          <m.div
            variants={container}
            initial='hidden'
            whileInView='visible'
            className='shadow-lg rounded-xl p-10 my-10 dark:bg-white max-w-2xl mx-auto lg:max-w-4xl'>
            <form 
              action='https://getform.io/f/e8b42a78-78e1-4bb4-9114-2cc23b941aa1'
              method='POST'
              onSubmit={formik.handleSubmit}
              variants={item} 
              className='font-poppins'>
              <div className=''>
                <label 
                  className={`text-xl ${formik.touched.name && formik.errors.name ? 'text-red-400' : ''}`}>
                {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input 
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  type='text'
                  name='name'
                  required
                  className='border drop-shadow-lg w-full my-2 h-10 rounded-lg p-4' placeholder='John Doe' />
              </div>
              <div className='mt-4'>
                <label 
                  className={`text-xl ${formik.touched.email && formik.errors.email ? 'text-red-400' : ''}`}>
                {formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}
                </label>
                <input 
                required
                value={formik.values.email}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                type='email'
                name='email'
                className='border drop-shadow-lg w-full my-2 h-10 rounded-lg p-4' placeholder='example@domain.com' />
              </div>
              <div className='my-6'>
                <label 
                  className={`text-xl ${formik.touched.message && formik.errors.message ? 'text-red-400' : ''}`}>
                {formik.touched.message && formik.errors.message ? formik.errors.message : 'Message'}
                </label>
                <textarea
                required
                value={formik.values.message}
                onChange={formik.handleChange} 
                onBlur={formik.handleBlur}
                type='text'
                name='message'
                className='border drop-shadow-lg my-2 h-40 w-full rounded-lg p-4'
                placeholder='Enter a message...' 
                />
              </div>
              <m.div 
                transition={{duration: 0.2, ease: 'easeOut'}}
                whileHover={{ scale: 1.1 }}
                className='bg-gradient-to-r drop-shadow-lg from-cyan-500 to-purple-500 rounded-xl text-white text-xl'>
                <button type='submit' className='w-full h-10'>Send Message</button>
              </m.div>
            </form>
          </m.div>
        </section>
        <section>
          <div className='text-center pb-5 dark:text-white'>
            <footer>
             &copy; Copyright Brian Sanchez Portfolio All Rights Reserved
            </footer>
          </div>
        </section>
      </main>
    </div>
  )
}
